name: Auto_SA
on:
  workflow_dispatch:
jobs:
  AutoSyncProcess:
    runs-on: ubuntu-latest
    steps:
    - name: Env Install
      run: |
        curl -s https://api.myip.la/cn?json
        wget -q https://github.com/jonntd/gclone/releases/download/v1.52.13/gclone_1.52.13_Linux_x86_64.gz
        gunzip gclone_1.52.13_Linux_x86_64.gz
        sudo mv gclone_1.52.13_Linux_x86_64 /usr/bin/gclone
        chmod +x /usr/bin/gclone
        sudo apt install unrar -y -q
    - name: Inject Rclone config
      env:
        RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
      run: |
        wget -q https://github.com/$GITHUB_REPOSITORY/raw/main/accounts.rar
        unrar -p'${{ secrets.RAR_PSWD }}' e accounts.rar ~/accounts/
        index=`ls -l ~/accounts |grep "^-"|wc -l`
        mkdir -p ~/.config/rclone/
        cat >  ~/.config/rclone/rclone.conf  << EOF
        ${RCLONE_CONF/1.json/$((RANDOM%$index+1)).json}
        EOF
    - name: Rclone Synchronizing file
      run: |
        gclone copy ${{ secrets.AUTO_FILE_PATH }} --max-backlog 1000 --stats-log-level NOTICE -P --stats 30s --size-only --cache-chunk-total-size 20G --transfers=10 --onedrive-chunk-size 250M --drive-chunk-size 256M
